name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Run Snyk on frontend
      if: ${{ hashFiles('frontend/package.json') != '' }}
      run: snyk test --file=frontend/package.json --json > snyk-frontend-report.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk on backend
      if: ${{ hashFiles('backend/package.json') != '' }}
      run: snyk test --file=backend/package.json --json > snyk-backend-report.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload Snyk reports
      uses: actions/upload-artifact@v2
      with:
        name: snyk-reports
        path: |
          snyk-frontend-report.json
          snyk-backend-report.json

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config auto --json > semgrep-report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep-report.json
