name: Security Scan Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Snyk
      uses: snyk/actions/setup@v2
      with:
        version: 'latest'

    - name: Run Snyk to check for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --all-projects --json > snyk_report.json

    - name: Upload Snyk report
      uses: actions/upload-artifact@v2
      with:
        name: snyk-report
        path: snyk_report.json

    - name: Convert Snyk report to SARIF
      run: snyk-to-sarif --input snyk_report.json --output snyk_report.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk_report.sarif

  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Print Python version
      run: python --version

    - name: Run Semgrep
      run: semgrep --config auto --json > semgrep_report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep_report.json

    - name: Convert Semgrep report to SARIF
      run: semgrep --config auto --sarif > semgrep.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
