name: Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and navigate to directory
        run: mkdir additional && cd additional && git clone https://github.com/jai3747/APP- .

      - name: List files in directory
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: npm install
        
      - name: Install Snyk
        run: npm install -g snyk

      - name: Auth Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run: snyk test 

      - name: Monitor Snyk project
        run: snyk monitor 

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and navigate to directory
        run: mkdir additional && cd additional && git clone https://github.com/jai3747/APP- .

      - name: List files in directory
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config "p/ci" .
