name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Check for frontend package.json and run Snyk
      if: ${{ hashFiles('frontend/package.json') != '' }}
      run: snyk test --org=YOUR_ORG_NAME --file=frontend/package.json --json

    - name: Check for backend package.json and run Snyk
      if: ${{ hashFiles('backend/package.json') != '' }}
      run: snyk test --org=YOUR_ORG_NAME --file=backend/package.json --json

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config auto --json > semgrep-report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep-report.json
