name: Semgrep Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  semgrep:
    runs-on: ubuntu-latest
    needs: semgrep-sact

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Print Python version
      run: python --version

    - name: Run Semgrep
      run: semgrep --config auto --json --output semgrep_report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep_report.json

    - name: Convert Semgrep report to SARIF
      run: semgrep --config auto --sarif --output semgrep.sarif

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
