name: Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone additional repository
        run: git clone https://github.com/jai3747/APP-.git additional-repo

      - name: List files in cloned repository
        run: ls -R additional-repo

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: snyk test additional-repo

      - name: Monitor Snyk project
        run: snyk monitor additional-repo

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone additional repository
        run: git clone https://github.com/jai3747/APP-.git additional-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config "p/ci" additional-repo
